ROLE_GRANTS = {
    "ROOT_ADMIN": [
        "INSTITUTION_VIEW",
        "INSTITUTION_SETTINGS_MANAGE",
        "ADMIN_VIEW",
        "ADMIN_CREATE",
        "ADMIN_DISABLE",
        "ADMIN_ASSIGN_ROLE",
        "STUDENT_CREATE",
        "STUDENT_VIEW",
        "STUDENT_UPDATE",
        "TEACHER_CREATE",
        "TEACHER_VIEW",
        "TEACHER_UPDATE",
        "STAFF_CREATE",
        "STAFF_VIEW",
        "STAFF_UPDATE",
        "ADMISSION_INVITE_SEND",
        "ADMISSION_INVITE_RESEND",
        "ADMISSION_INVITE_REVOKE",
        "ACADEMIC_SESSION_MANAGE",
        "CLASS_SECTION_MANAGE",
        "FINANCE_VIEW",
        "FINANCE_MANAGE",
        "AUDIT_VIEW",
    ],
    "ADMISSION_ADMIN": [
        "INSTITUTION_VIEW",
        "STUDENT_CREATE",
        "STUDENT_VIEW",
        "STUDENT_UPDATE",
        "TEACHER_CREATE",
        "TEACHER_VIEW",
        "TEACHER_UPDATE",
        "STAFF_CREATE",
        "STAFF_VIEW",
        "STAFF_UPDATE",
        "ADMISSION_INVITE_SEND",
        "ADMISSION_INVITE_RESEND",
        "ADMISSION_INVITE_REVOKE",
    ],
    "FINANCE_ADMIN": ["INSTITUTION_VIEW", "FINANCE_VIEW", "FINANCE_MANAGE"],
    "PRINCIPAL": [
        "INSTITUTION_VIEW",
        "STUDENT_VIEW",
        "TEACHER_VIEW",
        "STAFF_VIEW",
        "ACADEMIC_SESSION_MANAGE",
        "CLASS_SECTION_MANAGE",
    ],
    "TEACHER": ["INSTITUTION_VIEW", "STUDENT_VIEW"],
    "STUDENT": ["INSTITUTION_VIEW"],
    "STAFF": ["INSTITUTION_VIEW"],
}
ROLE_DETAILS = {
    "ROOT_ADMIN": (
        "Root Administrator",
        "Institution owner with controlled administrative authority.",
    ),
    "ADMISSION_ADMIN": (
        "Admission Administrator",
        "Manages student, teacher, and staff onboarding without privilege-granting authority.",
    ),
    "FINANCE_ADMIN": ("Finance Administrator", "Views and manages institution finance workflows."),
    "PRINCIPAL": (
        "Principal",
        "Manages institution academic structure and views institutional records.",
    ),
    "TEACHER": ("Teacher", "Employee role for academic teaching responsibilities."),
    "STUDENT": ("Student", "Student membership within an institution."),
    "STAFF": ("Staff", "General non-teaching employee membership."),
}
PERMISSION_DETAILS = {
    "INSTITUTION_VIEW": "View institution information.",
    "INSTITUTION_SETTINGS_MANAGE": "Manage institution settings.",
    "ADMIN_VIEW": "View institution administrators.",
    "ADMIN_CREATE": "Invite an approved institution administrator role.",
    "ADMIN_DISABLE": "Suspend an institution administrator membership.",
    "ADMIN_ASSIGN_ROLE": "Assign an explicitly approved institution administrator role.",
    "STUDENT_CREATE": "Create student onboarding records.",
    "STUDENT_VIEW": "View tenant-scoped student records.",
    "STUDENT_UPDATE": "Update tenant-scoped student records.",
    "TEACHER_CREATE": "Create teacher onboarding records.",
    "TEACHER_VIEW": "View tenant-scoped teacher records.",
    "TEACHER_UPDATE": "Update tenant-scoped teacher records.",
    "STAFF_CREATE": "Create staff onboarding records.",
    "STAFF_VIEW": "View tenant-scoped staff records.",
    "STAFF_UPDATE": "Update tenant-scoped staff records.",
    "ADMISSION_INVITE_SEND": "Send admissions invitations.",
    "ADMISSION_INVITE_RESEND": "Rotate and resend pending admissions invitations.",
    "ADMISSION_INVITE_REVOKE": "Revoke pending admissions invitations.",
    "ACADEMIC_SESSION_MANAGE": "Manage academic sessions.",
    "CLASS_SECTION_MANAGE": "Manage class sections.",
    "FINANCE_VIEW": "View finance data.",
    "FINANCE_MANAGE": "Manage finance workflows.",
    "AUDIT_VIEW": "View institution audit history.",
}
